
FROM openjdk:11-jdk-slim
ADD target/spring-boot-backend-apirest-docker-1.jar spring-boot-backend-apirest-docker-1.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "spring-boot-backend-apirest-docker-1.jar"]